/* DO NOT EDIT THIS FILE - it is machine generated */
#include <jni.h>
/* Header for class main_java_MagicMirror */

#ifndef _Included_main_java_MagicMirror
#define _Included_main_java_MagicMirror
#ifdef __cplusplus
extern "C" {
#endif
#undef main_java_MagicMirror_minBetweenCalls
#define main_java_MagicMirror_minBetweenCalls 60L
/*
 * Class:     main_java_MagicMirror
 * Method:    cMonitorOn
 * Signature: ()V
 */
JNIEXPORT void JNICALL Java_main_java_MagicMirror_cMonitorOn
  (JNIEnv *, jobject);

/*
 * Class:     main_java_MagicMirror
 * Method:    cMonitorOff
 * Signature: ()V
 */
JNIEXPORT void JNICALL Java_main_java_MagicMirror_cMonitorOff
  (JNIEnv *, jobject);

#ifdef __cplusplus
}
#endif
#endif
